#!/usr/bin/env bash
# Script that setup a nginx web server on our server + redirection.

sudo apt update -y && apt upgrade -y
sudo apt install nginx -y

# Index page
echo "Holberton School" >/var/www/html/index.nginx-debian.html

# Redirect to fabulous Rick Astley page
sudo sed -i '/listen \[::\]:80 default_server;/a\        rewrite ^\/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# 404 Page not Found
echo "Ceci n'est pas une page" >/var/www/html/custom_404.html
sudo sed -i '/listen \[::\]:80 default_server;/a\        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Served header
sed -i "/404 \/custom_404.html;$/a\        add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default



service nginx restart 
