#!/usr/bin/env bash
# Installs HAproxy and configures it
apt-get update -y
apt-get install -y haproxy

CONF="\
frontend main
	bind *:80
	mode http
	default_backend web-server

backend web-server
	balance roundrobin
	server 1206-web-01 15.237.58.224 check
	server 1206-web-02 15.188.33.70 check
"

echo "$CONF" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
