#!/usr/bin/env bash
# Script that sets up an Nginx web server on our server + redirection.

apt update -y && apt upgrade -y
apt install nginx -y

# Index page
echo 'Holberton School' | tee /var/www/html/index.html

# Configure redirection
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
    }
}
EOF

service nginx restart
