#!/usr/bin/env bash
# Script that setup a nginx web server on our server + redirection.

apt update -y && apt upgrade -y
apt install nginx -y

# Index page
echo "Holberton School" >/var/www/html/index.nginx-debian.html

# Redirect to fabulous Rick Astley page
sudo sed -i '/listen \[::\]:80 default_server;/a\        rewrite ^/$ http://www.domain2.com permanent;' /etc/nginx/sites-available/default

service nginx restart
sudo service nginx reload
