#!/usr/bin/env bash
# Script that setup a nginx web server on our server + redirection.

sudo apt update -y && apt upgrade -y
sudo apt install nginx -y

# Index page
echo "Holberton School" >/var/www/html/index.nginx-debian.h/redirect_metml

# Redirect to fabulous Rick Astley page
sudo sed -i '/listen \[::\]:80 default_server;/a\        rewrite ^\/redirect_me(.*)$ return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
