#!/usr/bin/env bash
# Script that sets up an nginx web server on our server + redirection.

sudo apt update -y && sudo apt upgrade -y
sudo apt install nginx -y

# Index page
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

# Redirect to fabulous Rick Astley page
sudo sed -i '/listen \[::\]:80 default_server;/a\        rewrite ^\/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# 404 Page not Found
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html >/dev/null
sudo sed -i '/listen \[::\]:80 default_server;/a\        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Reload and restart Nginx
sudo systemctl reload nginx
sudo systemctl restart nginx

# Verify custom 404 page
response=$(curl -s -o /dev/null -w "%{http_code}" localhost/xyz)
if [[ $response == "404" ]]; then
    echo "Custom 404 page returns 404 code"
else
    echo "Custom 404 page does not return 404 code"
fi
