#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
# Firewall port 80
sudo ufw allow http
# opcional para que el echo de index tenga permisos y funcione
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
# Index
# Ubuntu 14 /usr/share/nginx/html/index.html
# ubuntu 16 /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
# Redirection
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# Configure your Nginx server to have a custom 404 page that contains "ceci..."
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
# start server
service nginx start
